USE [master]
GO

/****** Object:  Database [MvcCrudDB]    Script Date: 1/9/2020 2:36:23 PM ******/
CREATE DATABASE [MvcCrudDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MvcCrudDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MvcCrudDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MvcCrudDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MvcCrudDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MvcCrudDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MvcCrudDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MvcCrudDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MvcCrudDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MvcCrudDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MvcCrudDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MvcCrudDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MvcCrudDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MvcCrudDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MvcCrudDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MvcCrudDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MvcCrudDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MvcCrudDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MvcCrudDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MvcCrudDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MvcCrudDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MvcCrudDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MvcCrudDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MvcCrudDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MvcCrudDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MvcCrudDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MvcCrudDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MvcCrudDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MvcCrudDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MvcCrudDB] SET  MULTI_USER 
GO

ALTER DATABASE [MvcCrudDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MvcCrudDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MvcCrudDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MvcCrudDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MvcCrudDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MvcCrudDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MvcCrudDB] SET  READ_WRITE 
GO

